service: log-everything # NOTE: update this with your service name

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - 'multipart/form-data'

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  stage: dev
  region: us-east-1

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'

functions:
  json-logger:
    handler: handler.jsonLogger
    events:
      - http:
          path: json-logger
          method: any
  
  plex-logger:
    handler: handler.plexLogger
    events:
      - http:
          path: plex-logger
          method: any